---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[serverspec-healthcheck::ruby2_install]
      - recipe[serverspec-healthcheck::serverspec_install]
    attributes:
  - name: healthcheck
    run_list:
      - recipe[serverspec-healthcheck::healthcheck]
    attributes:
      serverspec:
        user_spec_path: ""
